In [3]:
import numpy as np

In [4]:
data = [[1,2,3],[4,5,6],[7,8,9]]

a = np.array(data)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
a.dtype

dtype('int32')

In [6]:
a = a.astype(np.float32)
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [7]:
a[0][1]

2.0

In [8]:
a = np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [9]:
b = np.ones(12)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
b = np.zeros(12).reshape(2,3,2)
b

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [11]:
d = np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
e = np.zeros([3,4,2])
e

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [13]:
g = np.full((3,4),1000)
g

array([[1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000]])

In [14]:
data = np.arange(0,10).reshape(2,5)
data

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
data[0][0] = 100
data

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [16]:
data[0][1] = 1000
data

array([[ 100, 1000,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [17]:
np.mean(data) #mean

114.4

In [18]:
np.median(data) #median, data's number is even(10). so It's 5th number(6) and 6th number(7)'s mean(6.5) becomes it's median.

6.5

In [19]:
np.std(data) #standard deviation.

296.5485457728633

In [20]:
np.var(data) #variation

87941.04

In [21]:
np.sum(data)

1144

In [22]:
sum(data)

array([ 105, 1006,    9,   11,   13])

In [24]:
np.sum(data, axis=0)

array([ 105, 1006,    9,   11,   13])

In [25]:
np.sum(data, axis=1)

array([1109,   35])

In [27]:
np.max(data)

1000

In [28]:
np.min(data)

2

In [30]:
import pandas as pd

In [34]:
data = np.arange(0, 50, 10)
data

array([ 0, 10, 20, 30, 40])

In [35]:
a = pd.Series(data, index=['a','b','c','d','e'])
a

a     0
b    10
c    20
d    30
e    40
dtype: int32

In [36]:
b = pd.Series(data)
b

0     0
1    10
2    20
3    30
4    40
dtype: int32

In [37]:
a['b']

10

In [38]:
a.loc['b']

10

In [40]:
a.iloc[1]

10

In [41]:
a

a     0
b    10
c    20
d    30
e    40
dtype: int32

In [49]:
a + 10
a - 10
a * 10
a ** 2
a / 5
a // 5
a % 3

a    0
b    1
c    2
d    0
e    1
dtype: int32

In [50]:
a

a     0
b    10
c    20
d    30
e    40
dtype: int32

In [51]:
a > 15

a    False
b    False
c     True
d     True
e     True
dtype: bool

In [52]:
a[a > 15]

c    20
d    30
e    40
dtype: int32

In [53]:
a.add(100)

a    100
b    110
c    120
d    130
e    140
dtype: int32

In [54]:
a.sub(100)

a   -100
b    -90
c    -80
d    -70
e    -60
dtype: int32

In [55]:
a.mul(100)

a       0
b    1000
c    2000
d    3000
e    4000
dtype: int32

In [56]:
a.div(100)

a    0.0
b    0.1
c    0.2
d    0.3
e    0.4
dtype: float64

In [57]:
a.mod(3)

a    0
b    1
c    2
d    0
e    1
dtype: int32

In [58]:
a.min()

0

In [59]:
a.max()

40

In [60]:
a.sum()

100

In [61]:
a.mean()

20.0

In [62]:
a.median()

20.0

In [63]:
a.std()

15.811388300841896

In [64]:
a.var()

250.0

In [66]:
rawData = np.random.randint(50, 100, size = (4,3))
rawData

array([[74, 66, 77],
       [56, 79, 64],
       [73, 62, 62],
       [81, 88, 90]])

In [75]:
df = pd.DataFrame(rawData, 
                  index=['class1','class2','class1','class2'],
                  columns=['java','c','python'])
df

java   c  python
class1    74  66      77
class2    56  79      64
class1    73  62      62
class2    81  88      90

In [70]:
df['java']

class1    74
class2    56
class1    73
class2    81
Name: java, dtype: int32

In [72]:
# df[0] -> error

In [76]:
df

java   c  python
class1    74  66      77
class2    56  79      64
class1    73  62      62
class2    81  88      90

In [89]:
df['mean1'] = round((df['java'] + df['c'] + df['python'])/3, 2)
df

java   c  python   mean  mean1
class1    74  66      77  72.33  72.33
class2    56  79      64  66.33  66.33
class1    73  62      62  65.67  65.67
class2    81  88      90  86.33  86.33

In [78]:
df['na'] = np.nan
df

java   c  python   mean  na
class1    74  66      77  72.33 NaN
class2    56  79      64  66.33 NaN
class1    73  62      62  65.67 NaN
class2    81  88      90  86.33 NaN

In [93]:
del df['mean']
df

java   c  python
class1    74  66      77
class2    56  79      64
class1    73  62      62
class2    81  88      90

In [90]:
df[df.mean1 > 70]

java   c  python   mean  mean1
class1    74  66      77  72.33  72.33
class2    81  88      90  86.33  86.33

In [105]:
# df = df.drop(['mean1'],axis = 'columns')
# df

In [95]:
df = df.astype('float64')
df

java     c  python
class1  74.0  66.0    77.0
class2  56.0  79.0    64.0
class1  73.0  62.0    62.0
class2  81.0  88.0    90.0

In [97]:
df['python'][2] = np.nan
df

java     c  python
class1  74.0  66.0    77.0
class2  56.0  79.0    64.0
class1  73.0  62.0     NaN
class2  81.0  88.0    90.0

In [98]:
df.dropna(axis=0) # (axis=0,inplace=True)

java     c  python
class1  74.0  66.0    77.0
class2  56.0  79.0    64.0
class2  81.0  88.0    90.0

In [99]:
df

java     c  python
class1  74.0  66.0    77.0
class2  56.0  79.0    64.0
class1  73.0  62.0     NaN
class2  81.0  88.0    90.0

In [100]:
df.dropna(axis=1)

java     c
class1  74.0  66.0
class2  56.0  79.0
class1  73.0  62.0
class2  81.0  88.0

In [101]:
df.fillna('hello')

java     c python
class1  74.0  66.0   77.0
class2  56.0  79.0   64.0
class1  73.0  62.0  hello
class2  81.0  88.0   90.0

In [102]:
df.T

class1  class2  class1  class2
java      74.0    56.0    73.0    81.0
c         66.0    79.0    62.0    88.0
python    77.0    64.0     NaN    90.0

In [104]:
df

java     c  python
class1  74.0  66.0    77.0
class2  56.0  79.0    64.0
class1  73.0  62.0     NaN
class2  81.0  88.0    90.0

In [107]:
df.index = [['grade1','grade1','grade2','grade2'],['class1','class2','class1','class2']]
df

java     c  python
grade1 class1  74.0  66.0    77.0
       class2  56.0  79.0    64.0
grade2 class1  73.0  62.0     NaN
       class2  81.0  88.0    90.0

In [109]:
df.columns = [['sub','sub','main'],['java','c','python']]
df

sub         main
               java     c python
grade1 class1  74.0  66.0   77.0
       class2  56.0  79.0   64.0
grade2 class1  73.0  62.0    NaN
       class2  81.0  88.0   90.0

In [111]:
df['sub']['java']

grade1  class1    74.0
        class2    56.0
grade2  class1    73.0
        class2    81.0
Name: java, dtype: float64

In [112]:
df.iloc[0]

sub   java      74.0
      c         66.0
main  python    77.0
Name: (grade1, class1), dtype: float64

In [114]:
df.loc['grade1'].loc['class1']

sub   java      74.0
      c         66.0
main  python    77.0
Name: class1, dtype: float64

In [115]:
df

sub         main
               java     c python
grade1 class1  74.0  66.0   77.0
       class2  56.0  79.0   64.0
grade2 class1  73.0  62.0    NaN
       class2  81.0  88.0   90.0

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4 entries, ('grade1', 'class1') to ('grade2', 'class2')
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   (sub, java)     4 non-null      float64
 1   (sub, c)        4 non-null      float64
 2   (main, python)  3 non-null      float64
dtypes: float64(3)
memory usage: 384.0+ bytes


In [118]:
df.head() # show from index 0 to 4

sub         main
               java     c python
grade1 class1  74.0  66.0   77.0
       class2  56.0  79.0   64.0
grade2 class1  73.0  62.0    NaN
       class2  81.0  88.0   90.0

In [119]:
df.tail() # show from index -1 to -5

sub         main
               java     c python
grade1 class1  74.0  66.0   77.0
       class2  56.0  79.0   64.0
grade2 class1  73.0  62.0    NaN
       class2  81.0  88.0   90.0

In [122]:
df.describe() # 3 -> because of nan

sub              main
            java          c python
count   4.000000   4.000000    3.0
mean   71.000000  73.750000   77.0
std    10.614456  11.954776   13.0
min    56.000000  62.000000   64.0
25%    68.750000  65.000000   70.5
50%    73.500000  72.500000   77.0
75%    75.750000  81.250000   83.5
max    81.000000  88.000000   90.0

In [125]:
df.isnull()

sub          main
                java      c python
grade1 class1  False  False  False
       class2  False  False  False
grade2 class1  False  False   True
       class2  False  False  False

In [126]:
df.isnull().sum()

sub   java      0
      c         0
main  python    1
dtype: int64

In [127]:
a = pd.DataFrame(np.arange(1,10).reshape(3,3))
a

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [128]:
b = pd.Series(np.arange(10,40,10))
b

0    10
1    20
2    30
dtype: int32

In [129]:
pd.concat([a, b], axis=1)

0  1  2   0
0  1  2  3  10
1  4  5  6  20
2  7  8  9  30

In [130]:
pd.concat([a, b], axis=1, ignore_index=True)
# If you want to apply this action, you have to redefine a likes a = pd.concat([a, b], axis=1, ignore_index=True)

0  1  2   3
0  1  2  3  10
1  4  5  6  20
2  7  8  9  30

In [133]:
a.append(b, ignore_index=True)

0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  20  30